POST http://localhost:5201/v1/login HTTP/1.1
content-type: application/json
Authorization: Bearer lzm

{
    "username": "admin",
    "password": "123456"
}

###

GET http://localhost:5201/v1/login HTTP/1.1

###

POST http://localhost:5201/v1/user/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTk0MTEzNn0.wFUa6yG7k7OdNNzJ22mWANoOgwzjxZZY_UX8LsE3PXM

{
    "name": "hl",
    "phone": ""
}

### 
GET http://localhost:5201/v1/user/getuserlist?page=2 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTk0MTEzNn0.wFUa6yG7k7OdNNzJ22mWANoOgwzjxZZY_UX8LsE3PXM

###
GET http://localhost:5201/v1/user/getuserlist HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTk0MTEzNn0.wFUa6yG7k7OdNNzJ22mWANoOgwzjxZZY_UX8LsE3PXM


### 
POST http://localhost:5201/v1/user/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTk0MTEzNn0.wFUa6yG7k7OdNNzJ22mWANoOgwzjxZZY_UX8LsE3PXM

{
    "name":"hl3"
}

### 
POST http://localhost:5201/v1/user/update HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTk0MTEzNn0.wFUa6yG7k7OdNNzJ22mWANoOgwzjxZZY_UX8LsE3PXM

{
    "id":"28a44754-db83-4ce5-adb0-86da32b93221",
    "name":"TheShy",
    "phone":"17256481236"
}

### 
POST http://localhost:5201/v1/token/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTk0MTEzNn0.wFUa6yG7k7OdNNzJ22mWANoOgwzjxZZY_UX8LsE3PXM

{
    "id":"28a44754-db83-4ce5-adb0-86da32b93221"
}

### 
POST http://localhost:5201/v1/token/delete HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTk0MTEzNn0.wFUa6yG7k7OdNNzJ22mWANoOgwzjxZZY_UX8LsE3PXM

{
    "key":"c1bPHzUgwOy9ETr190HX4LqBQeJErvcSeI2lg3VGeco="
}

###
GET http://localhost:5201/v1/token/gettokenlist HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTk0MTEzNn0.wFUa6yG7k7OdNNzJ22mWANoOgwzjxZZY_UX8LsE3PXM