POST http://localhost:5201/v1/login HTTP/1.1
content-type: application/json
Authorization: Bearer lzm

{
    "username": "admin",
    "password": "123456"
}

###

GET http://localhost:5201/v1/login HTTP/1.1

###

POST http://localhost:5201/v1/user/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTg1MDcyOX0.SYhRvfCZZnMweB68vrfATADtNKFWqoea1YQMsuVl8zg

{
    "name": "hl",
    "phone": ""
}

### 
GET http://localhost:5201/v1/user/getuserlist?page=2 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTg1MDcyOX0.SYhRvfCZZnMweB68vrfATADtNKFWqoea1YQMsuVl8zg

###
GET http://localhost:5201/v1/user/getuserlist HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTg1MDcyOX0.SYhRvfCZZnMweB68vrfATADtNKFWqoea1YQMsuVl8zg


### 
POST http://localhost:5201/v1/user/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTg2MDExOH0.FtX4y01V8eraTZqy3pJOGhTH4pzvgZN1yMitwL37kBM

{
    "name":"hl3"
}

### 
POST http://localhost:5201/v1/user/update HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTcwMTg2MDExOH0.FtX4y01V8eraTZqy3pJOGhTH4pzvgZN1yMitwL37kBM

{
    "id":"e293b3a0-3769-46cb-be75-ed1636795eae",
    "name":"hlwinmax",
    "phone":"17256481236"
}
